# Generated by Django 2.2.2 on 2019-10-21 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='type',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
