# Generated by Django 2.2.2 on 2019-07-22 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apex_app', '0002_auto_20190722_0851'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='user_id',
        ),
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
