# Generated by Django 2.2.2 on 2019-08-02 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apex_app', '0004_post_user_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='User_details',
        ),
    ]
