# Generated by Django 2.2.2 on 2019-12-01 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apex_app', '0006_auto_20190802_0544'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_details',
            name='fb_details',
            field=models.TextField(blank=True, null=True),
        ),
    ]
