# Generated by Django 2.2.2 on 2019-12-01 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apex_app', '0007_user_details_fb_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_details',
            name='phone',
            field=models.TextField(blank=True, null=True),
        ),
    ]
