# Generated by Django 2.2.2 on 2019-12-01 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('type', models.CharField(max_length=255, null=True)),
                ('description', models.TextField(null=True)),
                ('image', models.CharField(max_length=255, null=True)),
                ('availability', models.BooleanField(default=1)),
                ('status', models.IntegerField(default=0)),
            ],
        ),
    ]
